w0rm/elm-physics

.travis.yml
tests/ConvexPolyhedron.elm

Run `elm-test` on travis ci, e.g. https://travis-ci.org/w0rm/elm-physics/jobs/403906900#L1119

Add travis support

---

Physics/NarrowPhase.elm

Implements the solution that was proposed in #12

Fix collision bug between a sphere and a convex

---

src/Physics.elm

Noticed a tiny thing. Examples are also using the delta version.

Update documentation for step function

---

src/Physics/NarrowPhase.elm
src/Physics/Solver.elm
src/Physics/SolverBody.elm
src/Physics/World.elm

For about ~30 boxes in the scene, this performs at 30-40fps, while the original performs at 20-30fps. So I'm going to merge this. Thanks @shuhei  🎉

Direct record update

---

benchmarks/NarrowPhase.elm
src/Internal/AABB.elm
src/Internal/Body.elm
src/Internal/ConvexPolyhedron.elm
src/Internal/NarrowPhase.elm
src/Internal/Shape.elm
src/Internal/Transform.elm
src/Physics/Body.elm
tests/ConvexPolyhedronTest.elm
tests/NarrowPhaseTest.elm

To reflect `setOrientation` in the new api

Rename quaternion to orientation

---

src/Internal/ConvexPolyhedron.elm
src/Internal/NarrowPhase.elm

Closes #48 
Sphere & plane collision had the wrong order of arguments.

Fix sphere plane collision

---

src/Internal/SolverBody.elm

This speeds up the solver even more, by inlining vector computations. The code becomes less understandable, so I kept the old code in the comments.

Inline vector computation on the hot path

---

elm.json
src/Internal/Constraint.elm
src/Internal/Equation.elm
src/Internal/Solver.elm
src/Internal/World.elm
src/Physics/Constraint.elm
src/Physics/World.elm

Started working on physical constraints, this introduces API and implements the pointToPoint constraint!

Constraints

---

src/Internal/Constraint.elm
src/Internal/Equation.elm
src/Physics/Constraint.elm

A hinge constraint fixes two points and limits the rotation axis. Useful for doors or wheels.

Rotational equation and hinge constraint

---

.gitignore
examples/Car.elm
examples/Drag.elm
src/Fixtures/NarrowPhase.elm
src/Internal/Body.elm
src/Internal/ConvexPolyhedron.elm
src/Internal/Matrix3.elm
src/Internal/NarrowPhase.elm
src/Internal/Quaternion.elm
src/Internal/Solver.elm
src/Internal/SolverBody.elm
src/Internal/World.elm
tests/NarrowPhaseTest.elm

Used Elm intellij plugin to delete unused code from the project.

Delete unused code

---

benchmarks/Convex.elm
benchmarks/ConvexConvex.elm
benchmarks/ConvexPolyhedron.elm
benchmarks/SphereConvex.elm
src/Collision/ConvexConvex.elm
src/Collision/PlaneConvex.elm
src/Collision/PlaneSphere.elm
src/Collision/SphereConvex.elm
src/Collision/SphereSphere.elm
src/Fixtures/Convex.elm
src/Fixtures/ConvexPolyhedron.elm
src/Fixtures/NarrowPhase.elm
src/Internal/AABB.elm
src/Internal/Contact.elm
src/Internal/Convex.elm
src/Internal/ConvexPolyhedron.elm
src/Internal/Equation.elm
src/Internal/NarrowPhase.elm
src/Internal/Shape.elm
src/Internal/Solver.elm
src/Internal/Vector3.elm
src/Physics/Debug.elm
src/Physics/Shape.elm
tests/BodyTest.elm
tests/ConvexConvexTest.elm
tests/ConvexPolyhedronTest.elm
tests/ConvexTest.elm
tests/SphereConvexTest.elm

* Moved collisions into their own modules
* Renamed ConvexPolyhedron -> Convex
* Updated tests and benchmarks

Refactor collisions

---

examples/Cloth.elm
src/Collision/ParticleConvex.elm
src/Collision/PlaneParticle.elm
src/Collision/SphereParticle.elm
src/Internal/AABB.elm
src/Internal/Constraint.elm
src/Internal/Equation.elm
src/Internal/NarrowPhase.elm
src/Internal/Shape.elm
src/Physics/Body.elm
src/Physics/Constraint.elm
src/Physics/Shape.elm

Closes #31
Also added support for the distance constraint and the Cloth demo:

Add support for the particle shape

---

examples/Car.elm
examples/Cloth.elm
examples/CollisionTest.elm
examples/Dominoes.elm
examples/Drag.elm
examples/Randomize.elm
src/Physics/Body.elm
src/Physics/Shape.elm

Change the API to rotate around Axis3d instead of Direction3d to avoid confusion with coordinate systems

Rotate around Axis3d

---

benchmarks/elm.json
elm.json
examples/Boxes.elm
examples/Car.elm
examples/Cloth.elm
examples/CollisionTest.elm
examples/Common/Meshes.elm
examples/Dominoes.elm
examples/Drag.elm
examples/Randomize.elm
examples/elm.json
src/Internal/Transform3d.elm
src/Physics/Body.elm
src/Physics/Shape.elm
tests/Transform3dFromFrame3dTest.elm

This would allow to construct shapes the same way as the common shapes in elm-3d-scene.

Create shapes from Block3d and Sphere3d

---

src/Internal/BroadPhase.elm
src/Internal/Contact.elm
src/Internal/Solver.elm
src/Internal/World.elm
src/Physics/Contact.elm
src/Physics/Debug.elm
src/Physics/World.elm

Added proper support for retrieving contacts between bodies in the world.

Support contacts

---

src/Internal/Body.elm
src/Internal/Equation.elm
src/Internal/Solver.elm
src/Internal/SolverBody.elm

* Apparently removing List.reverse made things worse in some cases — I put it back.
* Inline vlambda and wlambda vector components to reduce object allocations

Restore List.reverse and inline more things

---

examples/Boxes.elm
src/Internal/Equation.elm
src/Internal/Solver.elm
src/Internal/SolverBody.elm

This seems to improve performance!

Inline more things into solver

---

src/Internal/Equation.elm
src/Internal/Solver.elm

Simplified constructing equations

Improve equations construction

---

src/Internal/Body.elm
src/Internal/Equation.elm
src/Internal/Solver.elm
src/Internal/SolverBody.elm
src/Internal/World.elm
src/Physics/World.elm

Passing gravity down reduces allocations.

Remove addGravity iteration

---

src/Internal/BroadPhase.elm
src/Internal/Solver.elm

Crazy performance improvement that relies on the order of pairs from collisions.

Reduce array operations

---

README.md
examples/RaycastCar.elm
src/Physics/Body.elm

Working on the raycast vehicle example based on the existing implementations in [bullet](https://github.com/bulletphysics/bullet3/blob/master/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp) and [cannon.js](https://github.com/schteppe/cannon.js/blob/master/src/objects/RaycastVehicle.js)
The basic concept is explained here https://www.youtube.com/watch?v=LG1CtlFRmpU

Raycast Car
